function s = FK_af(in1)
%FK_AF
%    S = FK_AF(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    09-Jun-2017 15:36:04

q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = sin(q1);
t6 = t3.*3.379e-4;
t4 = t2-t6;
t5 = sin(q2);
s = [-atan((t2.*3.379e-4+t3+t4.*t5.*4.401e-2)./(t4.*cos(q2)));-asin(t2.*1.4870979e-5+t3.*4.401e-2-t4.*t5)];
