function s = FK_footimp(in1,in2,in3)
%FK_FOOTIMP
%    S = FK_FOOTIMP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    02-Jun-2017 12:14:40

q1 = in3(1,:);
q2 = in3(2,:);
ree2_1 = in1(2);
ree2_2 = in1(5);
ree2_3 = in1(8);
t2 = cos(q2);
t3 = cos(q1);
t4 = sin(q1);
t5 = sin(q2);
t6 = ree2_2.*t3;
t8 = ree2_3.*t4;
t7 = t6-t8;
s = [atan((ree2_1.*t2.*4.401e-2+ree2_2.*t4+ree2_3.*t3+t5.*t7.*4.401e-2)./(ree2_1.*t5-t2.*t7));asin(ree2_1.*t2-ree2_2.*t4.*4.401e-2-ree2_3.*t3.*4.401e-2+t5.*t7)];
