function s = FK_gaitEmul(in1)
%FK_GAITEMUL
%    S = FK_GAITEMUL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-Mar-2017 20:05:57

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
t2 = sin(q4);
t3 = cos(q4);
t4 = cos(q5);
t5 = cos(q6);
t6 = sin(q5);
t7 = sin(q6);
s = [q1+t2.*t4.*4.234e-1+t3.*t5.*1.5e-3-t2.*t6.*t7.*1.5e-3-5.347e-1;-q3+t2.*t5.*1.5e-3-t3.*t4.*4.234e-1+t3.*t6.*t7.*1.5e-3+6.508e-1;q2-t6.*4.234e-1-t4.*t7.*1.5e-3+3.78e-2;-atan((t2.*t7-t3.*t5.*t6)./(t3.*t4));atan((t4.*t7)./(t3.*t5-t2.*t6.*t7));asin(t2.*t5+t3.*t6.*t7)];
