function out1 = jacob_gaitEmul2(in1)
%JACOB_GAITEMUL2
%    OUT1 = JACOB_GAITEMUL2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Apr-2017 14:40:13

% Jacobian with q = [x z y theta_dp theta_ie theta_ml]
% and s = [x z y theta_dp theta_ie theta_ml]

q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
t2 = cos(q4);
t3 = sin(q4);
t4 = sin(q5);
t5 = cos(q5);
t6 = sin(q6);
t7 = cos(q6);
t9 = t3.*t7;
t10 = t2.*t4.*t6;
t8 = t9+t10;
t11 = t8.^2;
t12 = -t11+1.0;
t13 = 1.0./sqrt(t12);
t14 = 1.0./t5;
t15 = t3.*t6;
t18 = t2.*t4.*t7;
t16 = t15-t18;
t17 = 1.0./t2.^2;
t19 = 1.0./t2;
t20 = 1.0./t5.^2;
t21 = t16.^2;
t22 = t17.*t20.*t21;
t23 = t22+1.0;
t24 = 1.0./t23;
t25 = t2.*t7;
t27 = t3.*t4.*t6;
t26 = t25-t27;
t28 = 1.0./t26.^2;
t29 = t5.^2;
t30 = t6.^2;
t31 = t28.*t29.*t30;
t32 = t31+1.0;
t33 = 1.0./t32;
t34 = 1.0./t26;
t35 = t2.*t6;
t36 = t3.*t4.*t7;
t37 = t35+t36;
out1 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,t2.*t5.*4.234e-1-t3.*t7.*1.5e-3-t2.*t4.*t6.*1.5e-3,0.0,t3.*t5.*4.234e-1+t2.*t7.*1.5e-3-t3.*t4.*t6.*1.5e-3,t13.*t26,-t24.*(t14.*t19.*t37+t3.*t14.*t16.*t17),t5.*t6.*t8.*t28.*t33,t3.*t4.*(-4.234e-1)-t3.*t5.*t6.*1.5e-3,t5.*(-4.234e-1)+t4.*t6.*1.5e-3,t2.*t4.*4.234e-1+t2.*t5.*t6.*1.5e-3,t2.*t5.*t6.*t13,t24.*(t7-t4.*t16.*t19.*t20),-t33.*(t4.*t6.*t34-t3.*t28.*t29.*t30),t2.*t6.*(-1.5e-3)-t3.*t4.*t7.*1.5e-3,t5.*t7.*(-1.5e-3),t3.*t6.*(-1.5e-3)+t2.*t4.*t7.*1.5e-3,-t13.*t16,-t8.*t14.*t19.*t24,t33.*(t5.*t7.*t34+t5.*t6.*t28.*t37)],[6,6]);
