function out1 = jacob_footimp(in1,in2,in3)
%JACOB_FOOTIMP
%    OUT1 = JACOB_FOOTIMP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    02-Jun-2017 12:14:21

q1 = in3(1,:);
q2 = in3(2,:);
ree2_1 = in1(2);
ree2_2 = in1(5);
ree2_3 = in1(8);
t2 = cos(q1);
t3 = ree2_2.*t2;
t4 = sin(q1);
t5 = sin(q2);
t6 = cos(q2);
t7 = ree2_1.*t5;
t8 = ree2_3.*t4;
t9 = ree2_3.*t2;
t10 = ree2_2.*t4;
t11 = t9+t10;
t12 = t3-t8;
t18 = t6.*t12;
t13 = t7-t18;
t14 = 1.0./t13.^2;
t15 = ree2_1.*t6.*4.401e-2;
t16 = t5.*t12.*4.401e-2;
t17 = t9+t10+t15+t16;
t19 = 1.0./t13;
t20 = t17.^2;
t21 = t14.*t20;
t22 = t21+1.0;
t23 = 1.0./t22;
t24 = ree2_1.*t6;
t25 = t5.*t12;
t27 = ree2_3.*t2.*4.401e-2;
t28 = ree2_2.*t4.*4.401e-2;
t26 = t24+t25-t27-t28;
t29 = t26.^2;
t30 = -t29+1.0;
t31 = 1.0./sqrt(t30);
out1 = reshape([-t23.*(t19.*(-t3+t8+t5.*t11.*4.401e-2)+t6.*t11.*t14.*t17),-t31.*(ree2_2.*t2.*4.401e-2-ree2_3.*t4.*4.401e-2+t5.*t11),-t23.*(t19.*(ree2_1.*t5.*4.401e-2-t6.*t12.*4.401e-2)+t14.*t17.*(t24+t25)),-t13.*t31],[2,2]);
