function out1 = jacob_af(in1)
%JACOB_AF
%    OUT1 = JACOB_AF(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    09-Jun-2017 15:35:51

q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = cos(q2);
t5 = 1.0./t4;
t6 = t3.*3.379e-4;
t7 = t2.*3.379e-4;
t8 = t3+t7;
t9 = sin(q2);
t10 = t2-t6;
t11 = 1.0./t10.^2;
t12 = t9.*t10.*4.401e-2;
t13 = t3+t7+t12;
t14 = 1.0./t4.^2;
t15 = t13.^2;
t16 = t11.*t14.*t15;
t17 = t16+1.0;
t18 = 1.0./t17;
t20 = t2.*1.4870979e-5;
t21 = t3.*4.401e-2;
t22 = t9.*t10;
t19 = t20+t21-t22;
t23 = t19.^2;
t24 = -t23+1.0;
t25 = 1.0./sqrt(t24);
out1 = reshape([t18.*((t5.*(-t2+t6+t8.*t9.*4.401e-2))./(t2-t3.*3.379e-4)-t5.*t8.*t11.*t13),-t25.*(t2.*4.401e-2-t3.*1.4870979e-5+t8.*t9),-t18.*((t9.*t13.*t14)./t10+4.401e-2),t4.*t10.*t25],[2,2]);
